import { addTour, getProfile, getUserTours } from '@/app/api/supabase'
import { TRPCReactProvider } from '@/trpc/react'
import type { Metadata } from 'next'
import { DM_Mono } from 'next/font/google'
import { headers } from 'next/headers'
import { DBActionsProvider } from '../contexts'
import './globals.css'

/**
 * I don't know why but for some reason `Next` renders a fallback font when not
 * setting `preload: false`
 *
 * @todo This happens when wifi connection is slow, I will keep this for
 *   reference
 */
const dmMono = DM_Mono({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
  // preload: false,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const actions = {
  addTour,
  getProfile,
  getUserTours,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${dmMono.className} bg-neutral-900 text-white`}>
        <TRPCReactProvider headers={headers()}>
          <DBActionsProvider actions={actions}>{children}</DBActionsProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
