import { DBActionsProvider } from '@/contexts'
import { createClient } from '@/helpers/serverHelpers'
import { getSession, getUser } from '@/supabase/helpers'
import { TRPCReactProvider } from '@/trpc/react'
import type { Metadata } from 'next'
import { DM_Mono } from 'next/font/google'
import { headers } from 'next/headers'
import { addTour, deleteTour, getProfile, getUserTours } from './api/supabase'
import './globals.css'

/**
 * I don't know why but for some reason `Next` renders a fallback font when not
 * setting `preload: false`
 *
 * @todo This happens when wifi connection is slow, I will keep this for
 *   reference. Also move this inside the `font` folder and import it from
 *   there
 */
const dmMono = DM_Mono({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
  // preload: false,
})

/**
 * @todo This is incomplete. Also check if you can move this elsewhere and
 *   import it here
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  /**
   * @todo This is not working, we should get the `userId` and use it to fetch
   *   tours
   */
  const session = await getSession()

  let userToursIds
  if (session) {
    const supabase = createClient()
    const { id } = (await getUser(supabase)) || {}

    if (id) {
      const userTours = await getUserTours(id)
      userToursIds = userTours?.map((tour) => tour.id)
    } else userToursIds = []
  }

  /**
   * @todo Maybe put this into a `generateDBActions` function and move it
   *   elsewhere
   */
  const actions = {
    addTour,
    getProfile,
    userToursIds: userToursIds || [],
    deleteTour,
    session,
  }
  return (
    <html lang='en'>
      <body className={`${dmMono.className} bg-neutral-900 text-white`}>
        <TRPCReactProvider headers={headers()}>
          <DBActionsProvider actions={actions}>{children}</DBActionsProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
